from PhysicsTools.NanoAODTools.postprocessing.framework.datamodel import Collection, Object
from PhysicsTools.NanoAODTools.postprocessing.framework.eventloop import Module
from PhysicsTools.NanoAODTools.postprocessing.framework.postprocessor import PostProcessor
from importlib import import_module
import os
import sys
import ROOT
import numpy as np
ROOT.PyConfig.IgnoreCommandLineOptions = True


class HistProd(Module):
    def __init__(self,datamc):
        self.writeHistFile = True
	self.datamc = datamc
    def beginJob(self, histFile=None, histDirName=None):
	Module.beginJob(self, histFile, histDirName)
	MuonMuon= False

	self.Central_Scale_Dist= ROOT.TH1D("Central Scale Factor Distritution", "Central Scale Factor Distribution", 1000, 0,100)
	self.addObject(self.Central_Scale_Dist)
	self.Upper_Scale_Dist = ROOT.TH1D("Upper Scale Factor Distribution", "Upper Scale Factor Distribution", 1000, 0,100)
	self.addObject(self.Upper_Scale_Dist)
	self.Lower_Scale_Dist = ROOT.TH1D("Lower Scale Factor Distribution", "Lower Scale Factor Distribution", 1000, 0,100)
	self.addObject(self.Lower_Scale_Dist)
	self.Rochester_Scale_Dist = ROOT.TH1D("Rochester Corrections", "Rochester Corrections Distribution", 1000, 0.98,1.02)
        self.addObject(self.Rochester_Scale_Dist)
	self.ID_ISO_Trig_Scale_Dist=ROOT.TH1D("ID ISO Trig Distribution", "ID ISO Trig Distribution", 1000, 0.94,1.05)
        self.addObject(self.ID_ISO_Trig_Scale_Dist)
	self.Pileup_Central_Scale_Dist=ROOT.TH1D("Central Pileup Distribution", "Central Pileup Distribution", 1000, 0,3)
        self.addObject(self.Pileup_Central_Scale_Dist)
	self.Pileup_Upper_Scale_Dist=ROOT.TH1D("Upper Pileup Distribution", "Upper Pileup Distribution", 1000, 0,3)
        self.addObject(self.Pileup_Upper_Scale_Dist)
	self.Pileup_Lower_Scale_Dist=ROOT.TH1D("Lower Pileup Distribution", "Lower Pileup Distribution", 1000, 0,3)
	self.addObject(self.Pileup_Lower_Scale_Dist)
    	self.HEM_Scale_Dist=ROOT.TH1D("HEM Scale Factor Distribution","HEM Scale Factor Distribution",50,0,1.2)
    	self.addObject(self.HEM_Scale_Dist)
	self.GnJets_corrected=ROOT.TH1D("Corrected GnJets","Corrected GnJets",100,0,6)
	self.addObject(self.GnJets_corrected)
	self.GnJets_corrected_c=ROOT.TH1D("Corrected GnJets_c","Corrected GnJets_c",100,0,6)
        self.addObject(self.GnJets_corrected_c)
	self.GnJets_corrected_p=ROOT.TH1D("Corrected GnJets_p","Corrected GnJets_p",100,0,6)
        self.addObject(self.GnJets_corrected_p)
	self.GnJets_corrected_m=ROOT.TH1D("Corrected GnJets_m","Corrected GnJets_m",100,0,6)
        self.addObject(self.GnJets_corrected_m)


	self.MCTC=ROOT.TH1D("Charge Sign Comparison of Muon and Tau","Charge Sign Comparison of Muon and Tau",100,-0.2,1.2)
        self.addObject(self.MCTC)

	self.Z_massTau_j0=ROOT.TH1D("Z mass Tau jets = 0 ","Z mass Tau jets = 0 ",100,0,400)
        self.addObject(self.Z_massTau_j0)
	self.Z_massTau_j0_c=ROOT.TH1D("Z mass Tau jets = 0 c","Z mass Tau jets = 0 c",100,0,400)
        self.addObject(self.Z_massTau_j0_c)
	self.Z_massTau_j0_p=ROOT.TH1D("Z mass Tau jets = 0 p","Z mass Tau jets = 0 p",100,0,400)
        self.addObject(self.Z_massTau_j0_p)
	self.Z_massTau_j0_m=ROOT.TH1D("Z mass Tau jets = 0 m","Z mass Tau jets = 0 m",100,0,400)
        self.addObject(self.Z_massTau_j0_m)

        self.Z_massTau_j1=ROOT.TH1D("Z mass Tau jets = 1 ","Z mass Tau jets = 1 ",100,0,400)
        self.addObject(self.Z_massTau_j1)
        self.Z_massTau_j1_c=ROOT.TH1D("Z mass Tau jets = 1 c","Z mass Tau jets = 1 c",100,0,400)
        self.addObject(self.Z_massTau_j1_c)
        self.Z_massTau_j1_p=ROOT.TH1D("Z mass Tau jets = 1 p","Z mass Tau jets = 1 p",100,0,400)
        self.addObject(self.Z_massTau_j1_p)
        self.Z_massTau_j1_m=ROOT.TH1D("Z mass Tau jets = 1 m","Z mass Tau jets = 1 m",100,0,400)
        self.addObject(self.Z_massTau_j1_m)

        self.Z_massTau_j2=ROOT.TH1D("Z mass Tau jets = 2 ","Z mass Tau jets = 2 ",100,0,400)
        self.addObject(self.Z_massTau_j2)
        self.Z_massTau_j2_c=ROOT.TH1D("Z mass Tau jets = 2 c","Z mass Tau jets = 2 c",100,0,400)
        self.addObject(self.Z_massTau_j2_c)
        self.Z_massTau_j2_p=ROOT.TH1D("Z mass Tau jets = 2 p","Z mass Tau jets = 2 p",100,0,400)
        self.addObject(self.Z_massTau_j2_p)
        self.Z_massTau_j2_m=ROOT.TH1D("Z mass Tau jets = 2 m","Z mass Tau jets = 2 m",100,0,400)
        self.addObject(self.Z_massTau_j2_m)

        self.Z_massTau_j3=ROOT.TH1D("Z mass Tau jets = 3 ","Z mass Tau jets = 3 ",100,0,400)
        self.addObject(self.Z_massTau_j3)
        self.Z_massTau_j3_c=ROOT.TH1D("Z mass Tau jets = 3 c","Z mass Tau jets = 3 c",100,0,400)
        self.addObject(self.Z_massTau_j3_c)
        self.Z_massTau_j3_p=ROOT.TH1D("Z mass Tau jets = 3 p","Z mass Tau jets = 3 p",100,0,400)
        self.addObject(self.Z_massTau_j3_p)
        self.Z_massTau_j3_m=ROOT.TH1D("Z mass Tau jets = 3 m","Z mass Tau jets = 3 m",100,0,400)
        self.addObject(self.Z_massTau_j3_m)

        self.Z_massTau_j4=ROOT.TH1D("Z mass Tau jets = 4 ","Z mass Tau jets = 4 ",100,0,400)
        self.addObject(self.Z_massTau_j4)
        self.Z_massTau_j4_c=ROOT.TH1D("Z mass Tau jets = 4 c","Z mass Tau jets = 4 c",100,0,400)
        self.addObject(self.Z_massTau_j4_c)
        self.Z_massTau_j4_p=ROOT.TH1D("Z mass Tau jets = 4 p","Z mass Tau jets = 4 p",100,0,400)
        self.addObject(self.Z_massTau_j4_p)
        self.Z_massTau_j4_m=ROOT.TH1D("Z mass Tau jets = 4 m","Z mass Tau jets = 4 m",100,0,400)
        self.addObject(self.Z_massTau_j4_m)

        self.Z_massTau_j5=ROOT.TH1D("Z mass Tau jets = 5 ","Z mass Tau jets = 5 ",100,0,400)
        self.addObject(self.Z_massTau_j5)
        self.Z_massTau_j5_c=ROOT.TH1D("Z mass Tau jets = 5 c","Z mass Tau jets = 5 c",100,0,400)
        self.addObject(self.Z_massTau_j5_c)
        self.Z_massTau_j5_p=ROOT.TH1D("Z mass Tau jets = 5 p","Z mass Tau jets = 5 p",100,0,400)
        self.addObject(self.Z_massTau_j5_p)
        self.Z_massTau_j5_m=ROOT.TH1D("Z mass Tau jets = 5 m","Z mass Tau jets = 5 m",100,0,400)
        self.addObject(self.Z_massTau_j5_m)

    	self.GnMuon_original = ROOT.TH1D("GnMuon_original", "GnMuon_original", 100, 0, 10)
    	self.addObject(self.GnMuon_original)
    	self.GMuon_pt_original = ROOT.TH1D("GMuon_pt_original", "GMuon_pt_original", 100, 0, 400)
    	self.addObject(self.GMuon_pt_original)
    	self.GMuon_eta_original = ROOT.TH1D("GMuon_eta_original", "GMuon_eta_original", 100, -4, 4)
    	self.addObject(self.GMuon_eta_original)
    	self.GMuon_phi_original = ROOT.TH1D("GMuon_phi_original", "GMuon_phi_original", 100, -4, 4)
    	self.addObject(self.GMuon_phi_original)
    	self.GMuon_mass_original = ROOT.TH1D("GMuon_mass_original", "GMuon_mass_original", 100, 0, 0.2)
    	self.addObject(self.GMuon_mass_original)

        self.GMuon_charge_original = ROOT.TH1D("GMuon_charge_original", "GMuon_charge_original", 100, -1.2, 1.2)
    	self.addObject(self.GMuon_charge_original)
        self.GTau_charge_original = ROOT.TH1D("GTau_charge_original", "GTau_charge_original", 100, -10, 10)
    	self.addObject(self.GTau_charge_original)

        self.GnTau_original = ROOT.TH1D("GnTau_original", "GnTau_original", 100, 0, 10)
        self.addObject(self.GnTau_original)
        self.GTau_pt_original = ROOT.TH1D("GTau_pt_original", "GTau_pt_original", 100, 0, 400)
        self.addObject(self.GTau_pt_original)
        self.GTau_eta_original = ROOT.TH1D("GTau_eta_original", "GTau_eta_original", 100, -4, 4)
        self.addObject(self.GTau_eta_original)
        self.GTau_phi_original = ROOT.TH1D("GTau_phi_original", "GTau_phi_original", 100, -4, 4)
        self.addObject(self.GTau_phi_original)
        self.GTau_mass_original = ROOT.TH1D("GTau_mass_original", "GTau_mass_original", 100, 0, 4)
        self.addObject(self.GTau_mass_original)
	self.GNPV_original = ROOT.TH1D("GNPV_original", "GNPV_original", 100, 0, 10)
        self.addObject(self.GNPV_original)
        self.Z_massTau_original = ROOT.TH1D("Z_massTau_original", "Z_massTau_original", 100, 0, 400)
        self.addObject(self.Z_massTau_original)
        self.Z_massTP_original = ROOT.TH1D("Z_massTP_original", "Z_massTP_original", 100, 0, 400)
        self.addObject(self.Z_massTP_original)
        self.Z_massTPIso_original = ROOT.TH1D("Z_massTPIso_original", "Z_massTPIso_original", 100, 0, 400)
        self.addObject(self.Z_massTPIso_original)
        self.Z_massTP3track_original = ROOT.TH1D("Z_massTP3track_original", "Z_massTP3track_original", 100, 0, 400)
        self.addObject(self.Z_massTP3track_original)
        self.GTau_iso_pt_original = ROOT.TH1D("GTau_iso_pt_original", "GTau_iso_pt_original", 100, 0, 400)
        self.addObject(self.GTau_iso_pt_original)
        self.GTau_noiso_pt_original = ROOT.TH1D("GTau_noiso_pt_original", "GTau_noiso_pt_original", 100, 0, 400)
        self.addObject(self.GTau_noiso_pt_original)
        self.GTwoProng_iso_pt_original = ROOT.TH1D("GTwoProng_iso_pt_original", "GTwoProng_iso_pt_original", 100, 0, 400)
        self.addObject(self.GTwoProng_iso_pt_original)
        self.GTwoProng_noiso_pt_original = ROOT.TH1D("GTwoProng_noiso_pt_original", "GTwoProng_noiso_pt_original", 100, 0, 400)
        self.addObject(self.GTwoProng_noiso_pt_original)
        self.GTwoProng_3track_pt_original = ROOT.TH1D("GTwoProng_3track_pt_original", "GTwoProng_3track_pt_original", 100, 0, 400)
        self.addObject(self.GTwoProng_3track_pt_original)
        self.GTau_iso_phi_original = ROOT.TH1D("GTau_iso_phi_original", "GTau_iso_phi_original", 100, -4, 4)
        self.addObject(self.GTau_iso_phi_original)
        self.GTau_noiso_phi_original = ROOT.TH1D("GTau_noiso_phi_original", "GTau_noiso_phi_original", 100, -4, 4)
        self.addObject(self.GTau_noiso_phi_original)
        self.GTwoProng_iso_phi_original = ROOT.TH1D("GTwoProng_iso_phi_original", "GTwoProng_iso_phi_original", 100, -4, 4)
        self.addObject(self.GTwoProng_iso_phi_original)
        self.GTwoProng_noiso_phi_original = ROOT.TH1D("GTwoProng_noiso_phi_original", "GTwoProng_noiso_phi_original", 100, -4, 4)
        self.addObject(self.GTwoProng_noiso_phi_original)
        self.GTwoProng_3track_phi_original = ROOT.TH1D("GTwoProng_3track_phi_original", "GTwoProng_3track_phi_original", 100,-4, 4)
        self.addObject(self.GTwoProng_3track_phi_original)
        self.GTau_iso_eta_original = ROOT.TH1D("GTau_iso_eta_original", "GTau_iso_eta_original", 100, -4, 4)
        self.addObject(self.GTau_iso_eta_original)
        self.GTau_noiso_eta_original = ROOT.TH1D("GTau_noiso_eta_original", "GTau_noiso_eta_original", 100,-4, 4)
        self.addObject(self.GTau_noiso_eta_original)
        self.GTwoProng_iso_eta_original = ROOT.TH1D("GTwoProng_iso_eta_original", "GTwoProng_iso_eta_original", 100, -4, 4)
        self.addObject(self.GTwoProng_iso_eta_original)
        self.GTwoProng_noiso_eta_original = ROOT.TH1D("GTwoProng_noiso_eta_original", "GTwoProng_noiso_eta_original", 100, -4, 4)
        self.addObject(self.GTwoProng_noiso_eta_original)
        self.GTwoProng_3track_eta_original = ROOT.TH1D("GTwoProng_3track_eta_original", "GTwoProng_3track_eta_original", 100, -4, 4)
        self.addObject(self.GTwoProng_3track_eta_original)
        self.TPTauDeltaR_original = ROOT.TH1D("TPTauDeltaR_original", "TPTauDeltaR_original", 100, 0, 0.5)
        self.addObject(self.TPTauDeltaR_original)
        self.GTPnTracks_original = ROOT.TH1D("GTPnTracks_original", "GTPnTracks_original", 100, 0, 10)
        self.addObject(self.GTPnTracks_original)
        self.GMET_original = ROOT.TH1D("GMET_original", "GMET_original", 100, 0, 800)
        self.addObject(self.GMET_original)

#	self.GMuon_pt2_original = ROOT.TH1D("GMuon_pt2_original", "GMuon_pt2_original", 100, 0, 400)
#        self.addObject(self.GMuon_pt2_original)
#        self.GMuon_eta2_original = ROOT.TH1D("GMuon_eta2_original", "GMuon_eta2_original", 100, -4, 4)
#        self.addObject(self.GMuon_eta2_original)
#        self.GMuon_phi2_original = ROOT.TH1D("GMuon_phi2_original", "GMuon_phi2_original", 100, -4, 4)
#        self.addObject(self.GMuon_phi2_original)
#        self.GMuon_mass2_original = ROOT.TH1D("GMuon_mass2_original", "GMuon_mass2_original", 100, 0, 4)
#        self.addObject(self.GMuon_mass2_original)
#	self.Z_massMuonMuon_original = ROOT.TH1D("Z_massMuonMuon_original","Z_massMuonMuon_original", 100, 0, 400)
# 	self.addObject(self.Z_massMuonMuon_original)



        self.GMuon_charge_m = ROOT.TH1D("GMuon_charge_m", "GMuon_charge_m", 100, -1.2, 1.2)
    	self.addObject(self.GMuon_charge_m)
        self.GTau_charge_m = ROOT.TH1D("GTau_charge_m", "GTau_charge_m", 100, -10, 10)
    	self.addObject(self.GTau_charge_m)
	self.GnMuon_m = ROOT.TH1D("GnMuon_m", "GnMuon_m", 100, 0, 10)
      	self.addObject(self.GnMuon_m)
      	self.GMuon_pt_m = ROOT.TH1D("GMuon_pt_m", "GMuon_pt_m", 100, 0, 400)
      	self.addObject(self.GMuon_pt_m)
      	self.GMuon_eta_m = ROOT.TH1D("GMuon_eta_m", "GMuon_eta_m", 100, -4, 4)
      	self.addObject(self.GMuon_eta_m)
      	self.GMuon_phi_m = ROOT.TH1D("GMuon_phi_m", "GMuon_phi_m", 100, -4, 4)
      	self.addObject(self.GMuon_phi_m)
      	self.GMuon_mass_m = ROOT.TH1D("GMuon_mass_m", "GMuon_mass_m", 100, 0, 0.2)
      	self.addObject(self.GMuon_mass_m)
        self.GnTau_m = ROOT.TH1D("GnTau_m", "GnTau_m", 100, 0, 10)
        self.addObject(self.GnTau_m)
        self.GTau_pt_m = ROOT.TH1D("GTau_pt_m", "GTau_pt_m", 100, 0, 400)
        self.addObject(self.GTau_pt_m)
        self.GTau_eta_m = ROOT.TH1D("GTau_eta_m", "GTau_eta_m", 100, -4, 4)
        self.addObject(self.GTau_eta_m)
        self.GTau_phi_m = ROOT.TH1D("GTau_phi_m", "GTau_phi_m", 100, -4, 4)
        self.addObject(self.GTau_phi_m)
        self.GTau_mass_m = ROOT.TH1D("GTau_mass_m", "GTau_mass_m", 100, 0, 4)
        self.addObject(self.GTau_mass_m)
        self.GNPV_m = ROOT.TH1D("GNPV_m", "GNPV_m", 100, 0, 10)
        self.addObject(self.GNPV_m)
        self.Z_massTau_m = ROOT.TH1D("Z_massTau_m", "Z_massTau_m", 100, 0, 400)
        self.addObject(self.Z_massTau_m)
        self.Z_massTP_m = ROOT.TH1D("Z_massTP_m", "Z_massTP_m", 100, 0, 400)
        self.addObject(self.Z_massTP_m)
        self.Z_massTPIso_m = ROOT.TH1D("Z_massTPIso_m", "Z_massTPIso_m", 100, 0, 400)
        self.addObject(self.Z_massTPIso_m)
        self.Z_massTP3track_m = ROOT.TH1D("Z_massTP3track_m", "Z_massTP3track_m", 100, 0, 400)
        self.addObject(self.Z_massTP3track_m)
        self.GTau_iso_pt_m = ROOT.TH1D("GTau_iso_pt_m", "GTau_iso_pt_m", 100, 0, 400)
        self.addObject(self.GTau_iso_pt_m)
        self.GTau_noiso_pt_m = ROOT.TH1D("GTau_noiso_pt_m", "GTau_noiso_pt_m", 100, 0, 400)
        self.addObject(self.GTau_noiso_pt_m)
        self.GTwoProng_iso_pt_m = ROOT.TH1D("GTwoProng_iso_pt_m", "GTwoProng_iso_pt_m", 100, 0, 400)
        self.addObject(self.GTwoProng_iso_pt_m)
        self.GTwoProng_noiso_pt_m = ROOT.TH1D("GTwoProng_noiso_pt_m", "GTwoProng_noiso_pt_m", 100, 0, 400)
        self.addObject(self.GTwoProng_noiso_pt_m)
        self.GTwoProng_3track_pt_m = ROOT.TH1D("GTwoProng_3track_pt_m", "GTwoProng_3track_pt_m", 100, 0, 400)
        self.addObject(self.GTwoProng_3track_pt_m)
        self.GTau_iso_phi_m = ROOT.TH1D("GTau_iso_phi_m", "GTau_iso_phi_m", 100, -4, 4)
        self.addObject(self.GTau_iso_phi_m)
        self.GTau_noiso_phi_m = ROOT.TH1D("GTau_noiso_phi_m", "GTau_noiso_phi_m", 100, -4, 4)
        self.addObject(self.GTau_noiso_phi_m)
        self.GTwoProng_iso_phi_m = ROOT.TH1D("GTwoProng_iso_phi_m", "GTwoProng_iso_phi_m", 100, -4, 4)
        self.addObject(self.GTwoProng_iso_phi_m)
        self.GTwoProng_noiso_phi_m = ROOT.TH1D("GTwoProng_noiso_phi_m", "GTwoProng_noiso_phi_m", 100, -4, 4)
        self.addObject(self.GTwoProng_noiso_phi_m)
        self.GTwoProng_3track_phi_m = ROOT.TH1D("GTwoProng_3track_phi_m", "GTwoProng_3track_phi_m", 100,-4, 4)
        self.addObject(self.GTwoProng_3track_phi_m)
        self.GTau_iso_eta_m = ROOT.TH1D("GTau_iso_eta_m", "GTau_iso_eta_m", 100, -4, 4)
        self.addObject(self.GTau_iso_eta_m)
        self.GTau_noiso_eta_m = ROOT.TH1D("GTau_noiso_eta_m", "GTau_noiso_eta_m", 100,-4, 4)
        self.addObject(self.GTau_noiso_eta_m)
        self.GTwoProng_iso_eta_m = ROOT.TH1D("GTwoProng_iso_eta_m", "GTwoProng_iso_eta_m", 100, -4, 4)
        self.addObject(self.GTwoProng_iso_eta_m)
        self.GTwoProng_noiso_eta_m = ROOT.TH1D("GTwoProng_noiso_eta_m", "GTwoProng_noiso_eta_m", 100, -4, 4)
        self.addObject(self.GTwoProng_noiso_eta_m)
        self.GTwoProng_3track_eta_m = ROOT.TH1D("GTwoProng_3track_eta_m", "GTwoProng_3track_eta_m", 100, -4, 4)
        self.addObject(self.GTwoProng_3track_eta_m)
        self.TPTauDeltaR_m = ROOT.TH1D("TPTauDeltaR_m", "TPTauDeltaR_m", 100, 0, 0.5)
        self.addObject(self.TPTauDeltaR_m)
        self.GTPnTracks_m = ROOT.TH1D("GTPnTracks_m", "GTPnTracks_m", 100, 0, 10)
        self.addObject(self.GTPnTracks_m)
        self.GMET_m = ROOT.TH1D("GMET_m", "GMET_m", 100, 0, 800)
        self.addObject(self.GMET_m)

 #       self.GMuon_pt2_m = ROOT.TH1D("GMuon_pt2_m", "GMuon_pt2_m", 100, 0, 400)
 #       self.addObject(self.GMuon_pt2_m)
 #       self.GMuon_eta2_m = ROOT.TH1D("GMuon_eta2_m", "GMuon_eta2_m", 100, -4, 4)
 #       self.addObject(self.GMuon_eta2_m)
 #       self.GMuon_phi2_m = ROOT.TH1D("GMuon_phi2_m", "GMuon_phi2_m", 100, -4, 4)
 #       self.addObject(self.GMuon_phi2_m)
 #       self.GMuon_mass2_m = ROOT.TH1D("GMuon_mass2_m", "GMuon_mass2_m", 100, 0, 4)
 #       self.addObject(self.GMuon_mass2_m)
 #       self.Z_massMuonMuon_m = ROOT.TH1D("Z_massMuonMuon_m","Z_massMuonMuon_m", 100, 0, 400)
 #       self.addObject(self.Z_massMuonMuon_m)

        self.GMuon_charge_p = ROOT.TH1D("GMuon_charge_p", "GMuon_charge_p", 100, -12., 1.2)
    	self.addObject(self.GMuon_charge_m)
        self.GTau_charge_p = ROOT.TH1D("GTau_charge_p", "GTau_charge_p", 100, -10, 10)
    	self.addObject(self.GTau_charge_p)

      	self.GnMuon_p = ROOT.TH1D("GnMuon_p", "GnMuon_p", 100, 0, 10)
      	self.addObject(self.GnMuon_p)
      	self.GMuon_pt_p = ROOT.TH1D("GMuon_pt_p", "GMuon_pt_p", 100, 0, 400)
      	self.addObject(self.GMuon_pt_p)
      	self.GMuon_eta_p = ROOT.TH1D("GMuon_eta_p", "GMuon_eta_p", 100, -4, 4)
      	self.addObject(self.GMuon_eta_p)
      	self.GMuon_phi_p = ROOT.TH1D("GMuon_phi_p", "GMuon_phi_p", 100, -4, 4)
     	self.addObject(self.GMuon_phi_p)
     	self.GMuon_mass_p = ROOT.TH1D("GMuon_mass_p", "GMuon_mass_p", 100, 0, 0.2)
      	self.addObject(self.GMuon_mass_p)
        self.GnTau_p = ROOT.TH1D("GnTau_p", "GnTau_p", 100, 0, 10)
        self.addObject(self.GnTau_p)
        self.GTau_pt_p = ROOT.TH1D("GTau_pt_p", "GTau_pt_p", 100, 0, 400)
        self.addObject(self.GTau_pt_p)
        self.GTau_eta_p = ROOT.TH1D("GTau_eta_p", "GTau_eta_p", 100, -4, 4)
        self.addObject(self.GTau_eta_p)
        self.GTau_phi_p = ROOT.TH1D("GTau_phi_p", "GTau_phi_p", 100, -4, 4)
        self.addObject(self.GTau_phi_p)
        self.GTau_mass_p = ROOT.TH1D("GTau_mass_p", "GTau_mass_p", 100, 0, 4)
        self.addObject(self.GTau_mass_p)
        self.GNPV_p = ROOT.TH1D("GNPV_p", "GNPV_p", 100, 0, 10)
        self.addObject(self.GNPV_p)
        self.Z_massTau_p = ROOT.TH1D("Z_massTau_p", "Z_massTau_p", 100, 0, 400)
        self.addObject(self.Z_massTau_p)
        self.Z_massTP_p = ROOT.TH1D("Z_massTP_p", "Z_massTP_p", 100, 0, 400)
        self.addObject(self.Z_massTP_p)
        self.Z_massTPIso_p = ROOT.TH1D("Z_massTPIso_p", "Z_massTPIso_p", 100, 0, 400)
        self.addObject(self.Z_massTPIso_p)
        self.Z_massTP3track_p = ROOT.TH1D("Z_massTP3track_p", "Z_massTP3track_p", 100, 0, 400)
        self.addObject(self.Z_massTP3track_p)
        self.GTau_iso_pt_p = ROOT.TH1D("GTau_iso_pt_p", "GTau_iso_pt_p", 100, 0, 400)
        self.addObject(self.GTau_iso_pt_p)
        self.GTau_noiso_pt_p = ROOT.TH1D("GTau_noiso_pt_p", "GTau_noiso_pt_p", 100, 0, 400)
        self.addObject(self.GTau_noiso_pt_p)
        self.GTwoProng_iso_pt_p = ROOT.TH1D("GTwoProng_iso_pt_p", "GTwoProng_iso_pt_p", 100, 0, 400)
        self.addObject(self.GTwoProng_iso_pt_p)
        self.GTwoProng_noiso_pt_p = ROOT.TH1D("GTwoProng_noiso_pt_p", "GTwoProng_noiso_pt_p", 100, 0, 400)
        self.addObject(self.GTwoProng_noiso_pt_p)
        self.GTwoProng_3track_pt_p = ROOT.TH1D("GTwoProng_3track_pt_p", "GTwoProng_3track_pt_p", 100, 0, 400)
        self.addObject(self.GTwoProng_3track_pt_p)
        self.GTau_iso_phi_p = ROOT.TH1D("GTau_iso_phi_p", "GTau_iso_phi_p", 100, -4, 4)
        self.addObject(self.GTau_iso_phi_p)
        self.GTau_noiso_phi_p = ROOT.TH1D("GTau_noiso_phi_p", "GTau_noiso_phi_p", 100, -4, 4)
        self.addObject(self.GTau_noiso_phi_p)
        self.GTwoProng_iso_phi_p = ROOT.TH1D("GTwoProng_iso_phi_p", "GTwoProng_iso_phi_p", 100, -4, 4)
        self.addObject(self.GTwoProng_iso_phi_p)
        self.GTwoProng_noiso_phi_p = ROOT.TH1D("GTwoProng_noiso_phi_p", "GTwoProng_noiso_phi_p", 100, -4, 4)
        self.addObject(self.GTwoProng_noiso_phi_p)
        self.GTwoProng_3track_phi_p = ROOT.TH1D("GTwoProng_3track_phi_p", "GTwoProng_3track_phi_p", 100,-4, 4)
        self.addObject(self.GTwoProng_3track_phi_p)
        self.GTau_iso_eta_p = ROOT.TH1D("GTau_iso_eta_p", "GTau_iso_eta_p", 100, -4, 4)
        self.addObject(self.GTau_iso_eta_p)
        self.GTau_noiso_eta_p = ROOT.TH1D("GTau_noiso_eta_p", "GTau_noiso_eta_p", 100,-4, 4)
        self.addObject(self.GTau_noiso_eta_p)
        self.GTwoProng_iso_eta_p = ROOT.TH1D("GTwoProng_iso_eta_p", "GTwoProng_iso_eta_p", 100, -4, 4)
        self.addObject(self.GTwoProng_iso_eta_p)
        self.GTwoProng_noiso_eta_p = ROOT.TH1D("GTwoProng_noiso_eta_p", "GTwoProng_noiso_eta_p", 100, -4, 4)
        self.addObject(self.GTwoProng_noiso_eta_p)
        self.GTwoProng_3track_eta_p = ROOT.TH1D("GTwoProng_3track_eta_p", "GTwoProng_3track_eta_p", 100, -4, 4)
        self.addObject(self.GTwoProng_3track_eta_p)
        self.TPTauDeltaR_p = ROOT.TH1D("TPTauDeltaR_p", "TPTauDeltaR_p", 100, 0, 0.5)
        self.addObject(self.TPTauDeltaR_p)
        self.GTPnTracks_p = ROOT.TH1D("GTPnTracks_p", "GTPnTracks_p", 100, 0, 10)
        self.addObject(self.GTPnTracks_p)
        self.GMET_p = ROOT.TH1D("GMET_p", "GMET_p", 100, 0, 800)
        self.addObject(self.GMET_p)

  #      self.GMuon_pt2_p = ROOT.TH1D("GMuon_pt2_p", "GMuon_pt2_p", 100, 0, 400)
  #      self.addObject(self.GMuon_pt2_p)
  #      self.GMuon_eta2_p = ROOT.TH1D("GMuon_eta2_p", "GMuon_eta2_p", 100, -4, 4)
  #      self.addObject(self.GMuon_eta2_p)
  #      self.GMuon_phi2_p = ROOT.TH1D("GMuon_phi2_p", "GMuon_phi2_p", 100, -4, 4)
  #      self.addObject(self.GMuon_phi2_p)
  #      self.GMuon_mass2_p = ROOT.TH1D("GMuon_mass2_p", "GMuon_mass2_p", 100, 0, 4)
  #      self.addObject(self.GMuon_mass2_p)
  #      self.Z_massMuonMuon_p = ROOT.TH1D("Z_massMuonMuon_p","Z_massMuonMuon_p", 100, 0, 400)
  #      self.addObject(self.Z_massMuonMuon_p)


        self.GMuon_charge_c = ROOT.TH1D("GMuon_charge_c", "GMuon_charge_c", 100, -1.2, 1.2)
    	self.addObject(self.GMuon_charge_c)
        self.GTau_charge_c = ROOT.TH1D("GTau_charge_c", "GTau_charge_c", 100, -10, 10)
    	self.addObject(self.GTau_charge_c)
	self.GPZeta_Tau_c =ROOT.TH1D("GPZeta_Tau_c", "GPZeta_Tau_c", 100, -100, 100)
        self.addObject(self.GPZeta_Tau_c)
        self.GPZeta_TP_c =ROOT.TH1D("GPZeta_TP_c", "GPZeta_TP_c", 100, -100, 100)
        self.addObject(self.GPZeta_TP_c)
	self.GTransMass_c= ROOT.TH1D("GTransMass_c","GTransMass_c",100,0,50)
	self.addObject(self.GTransMass_c)
	self.GnMuon_c = ROOT.TH1D("GnMuon_c", "GnMuon_c", 100, 0, 10)
      	self.addObject(self.GnMuon_c)
      	self.GMuon_pt_c = ROOT.TH1D("GMuon_pt_c", "GMuon_pt_c", 100, 0, 400)
      	self.addObject(self.GMuon_pt_c)
      	self.GMuon_eta_c = ROOT.TH1D("GMuon_eta_c", "GMuon_eta_c", 100, -4, 4)
      	self.addObject(self.GMuon_eta_c)
      	self.GMuon_phi_c = ROOT.TH1D("GMuon_phi_c", "GMuon_phi_c", 100, -4, 4)
      	self.addObject(self.GMuon_phi_c)
      	self.GMuon_mass_c = ROOT.TH1D("GMuon_mass_c", "GMuon_mass_c", 100, 0, 0.2)
      	self.addObject(self.GMuon_mass_c)
        self.GnTau_c = ROOT.TH1D("GnTau_c", "GnTau_c", 100, 0, 10)
        self.addObject(self.GnTau_c)
        self.GTau_pt_c = ROOT.TH1D("GTau_pt_c", "GTau_pt_c", 100, 0, 400)
        self.addObject(self.GTau_pt_c)
        self.GTau_eta_c = ROOT.TH1D("GTau_eta_c", "GTau_eta_c", 100, -4, 4)
        self.addObject(self.GTau_eta_c)
        self.GTau_phi_c = ROOT.TH1D("GTau_phi_c", "GTau_phi_c", 100, -4, 4)
        self.addObject(self.GTau_phi_c)
        self.GTau_mass_c = ROOT.TH1D("GTau_mass_c", "GTau_mass_c", 100, 0, 4)
        self.addObject(self.GTau_mass_c)
        self.GNPV_c = ROOT.TH1D("GNPV_c", "GNPV_c", 100, 0, 10)
        self.addObject(self.GNPV_c)
        self.Z_massTau_c = ROOT.TH1D("Z_massTau_c", "Z_massTau_c", 100, 0, 400)
        self.addObject(self.Z_massTau_c)
        self.Z_massTP_c = ROOT.TH1D("Z_massTP_c", "Z_massTP_c", 100, 0, 400)
        self.addObject(self.Z_massTP_c)
        self.Z_massTPIso_c = ROOT.TH1D("Z_massTPIso_c", "Z_massTPIso_c", 100, 0, 400)
        self.addObject(self.Z_massTPIso_c)
        self.Z_massTP3track_c = ROOT.TH1D("Z_massTP3track_c", "Z_massTP3track_c", 100, 0, 400)
        self.addObject(self.Z_massTP3track_c)
        self.GTau_iso_pt_c = ROOT.TH1D("GTau_iso_pt_c", "GTau_iso_pt_c", 100, 0, 400)
        self.addObject(self.GTau_iso_pt_c)
        self.GTau_noiso_pt_c = ROOT.TH1D("GTau_noiso_pt_c", "GTau_noiso_pt_c", 100, 0, 400)
        self.addObject(self.GTau_noiso_pt_c)
        self.GTwoProng_iso_pt_c = ROOT.TH1D("GTwoProng_iso_pt_c", "GTwoProng_iso_pt_c", 100, 0, 400)
        self.addObject(self.GTwoProng_iso_pt_c)
        self.GTwoProng_noiso_pt_c = ROOT.TH1D("GTwoProng_noiso_pt_c", "GTwoProng_noiso_pt_c", 100, 0, 400)
        self.addObject(self.GTwoProng_noiso_pt_c)
        self.GTwoProng_3track_pt_c = ROOT.TH1D("GTwoProng_3track_pt_c", "GTwoProng_3track_pt_c", 100, 0, 400)
        self.addObject(self.GTwoProng_3track_pt_c)
        self.GTau_iso_phi_c = ROOT.TH1D("GTau_iso_phi_c", "GTau_iso_phi_c", 100, -4, 4)
        self.addObject(self.GTau_iso_phi_c)
        self.GTau_noiso_phi_c = ROOT.TH1D("GTau_noiso_phi_c", "GTau_noiso_phi_c", 100, -4, 4)
        self.addObject(self.GTau_noiso_phi_c)
        self.GTwoProng_iso_phi_c = ROOT.TH1D("GTwoProng_iso_phi_c", "GTwoProng_iso_phi_c", 100, -4, 4)
        self.addObject(self.GTwoProng_iso_phi_c)
        self.GTwoProng_noiso_phi_c = ROOT.TH1D("GTwoProng_noiso_phi_c", "GTwoProng_noiso_phi_c", 100, -4, 4)
        self.addObject(self.GTwoProng_noiso_phi_c)
        self.GTwoProng_3track_phi_c = ROOT.TH1D("GTwoProng_3track_phi_c", "GTwoProng_3track_phi_c", 100,-4, 4)
        self.addObject(self.GTwoProng_3track_phi_c)
        self.GTau_iso_eta_c = ROOT.TH1D("GTau_iso_eta_c", "GTau_iso_eta_c", 100, -4, 4)
        self.addObject(self.GTau_iso_eta_c)
        self.GTau_noiso_eta_c = ROOT.TH1D("GTau_noiso_eta_c", "GTau_noiso_eta_c", 100,-4, 4)
        self.addObject(self.GTau_noiso_eta_c)
        self.GTwoProng_iso_eta_c = ROOT.TH1D("GTwoProng_iso_eta_c", "GTwoProng_iso_eta_c", 100, -4, 4)
        self.addObject(self.GTwoProng_iso_eta_c)
        self.GTwoProng_noiso_eta_c = ROOT.TH1D("GTwoProng_noiso_eta_c", "GTwoProng_noiso_eta_c", 100, -4, 4)
        self.addObject(self.GTwoProng_noiso_eta_c)
        self.GTwoProng_3track_eta_c = ROOT.TH1D("GTwoProng_3track_eta_c", "GTwoProng_3track_eta_c", 100, -4, 4)
        self.addObject(self.GTwoProng_3track_eta_c)
        self.TPTauDeltaR_c = ROOT.TH1D("TPTauDeltaR_c", "TPTauDeltaR_c", 100, 0, 0.1)
        self.addObject(self.TPTauDeltaR_c)
        self.GTPnTracks_c = ROOT.TH1D("GTPnTracks_c", "GTPnTracks_c", 100, 0, 10)
        self.addObject(self.GTPnTracks_c)
        self.GMET_c = ROOT.TH1D("GMET_c", "GMET_c", 100, 0, 800)
        self.addObject(self.GMET_c)

#        self.GMuon_pt2_c = ROOT.TH1D("GMuon_pt2_c", "GMuon_pt2_c", 100, 0, 400)
#        self.addObject(self.GMuon_pt2_c)
#        self.GMuon_eta2_c = ROOT.TH1D("GMuon_eta2_c", "GMuon_eta2_c", 100, -4, 4)
#        self.addObject(self.GMuon_eta2_c)
#        self.GMuon_phi2_c = ROOT.TH1D("GMuon_phi2_c", "GMuon_phi2_c", 100, -4, 4)
#        self.addObject(self.GMuon_phi2_c)
#        self.GMuon_mass2_c = ROOT.TH1D("GMuon_mass2_c", "GMuon_mass2_c", 100, 0, 4)
#        self.addObject(self.GMuon_mass2_c)
#        self.Z_massMuonMuon_c = ROOT.TH1D("Z_massMuonMuon_c","Z_massMuonMuon_c", 100, 0, 400)
#        self.addObject(self.Z_massMuonMuon_c)

	self.GJet_pt_c= ROOT.TH1D("GJet_pt_c","GJet_pt_c",100,0,400)
	self.addObject(self.GJet_pt_c)
        self.GJet_eta_c= ROOT.TH1D("GJet_eta_c","GJet_eta_c",100,-4,4)
        self.addObject(self.GJet_eta_c)
        self.GJet_phi_c= ROOT.TH1D("GJet_phi_c","GJet_phi_c",100,-4,4)
        self.addObject(self.GJet_phi_c)
        self.GJet_mass_c= ROOT.TH1D("GJet_mass_c","GJet_mass_c",100,0,400)
        self.addObject(self.GJet_mass_c)
        self.nTau_c= ROOT.TH1D("nTau_c","nTau_c",100,0,10)
        self.addObject(self.nTau_c)
        self.nMuon_c= ROOT.TH1D("nMuon_c","nMuon_c",100,0,10)
        self.addObject(self.nMuon_c)
	self.nJet_c=ROOT.TH1D("nJet_c","nJet_c",100,0,20)
	self.addObject(self.nJet_c)

	self.GJet_pt_p= ROOT.TH1D("GJet_pt_p","GJet_pt_p",100,0,400)
        self.addObject(self.GJet_pt_p)
        self.GJet_eta_p= ROOT.TH1D("GJet_eta_p","GJet_eta_p",100,-4,4)
        self.addObject(self.GJet_eta_p)
        self.GJet_phi_p= ROOT.TH1D("GJet_phi_p","GJet_phi_p",100,-4,4)
        self.addObject(self.GJet_phi_p)
        self.GJet_mass_p= ROOT.TH1D("GJet_mass_p","GJet_mass_p",100,0,400)
        self.addObject(self.GJet_mass_p)
        self.nTau_p= ROOT.TH1D("nTau_p","nTau_p",100,0,10)
        self.addObject(self.nTau_p)
        self.nMuon_p= ROOT.TH1D("nMuon_p","nMuon_p",100,0,10)
        self.addObject(self.nMuon_p)
        self.nJet_p=ROOT.TH1D("nJet_p","nJet_p",100,0,20)
        self.addObject(self.nJet_p)

        self.GJet_pt_m= ROOT.TH1D("GJet_pt_m","GJet_pt_m",100,0,400)
        self.addObject(self.GJet_pt_m)
        self.GJet_eta_m= ROOT.TH1D("GJet_eta_m","GJet_eta_m",100,-4,4)
        self.addObject(self.GJet_eta_m)
        self.GJet_phi_m= ROOT.TH1D("GJet_phi_m","GJet_phi_m",100,-4,4)
        self.addObject(self.GJet_phi_m)
        self.GJet_mass_m= ROOT.TH1D("GJet_mass_m","GJet_mass_m",100,0,400)
        self.addObject(self.GJet_mass_m)
        self.nTau_m= ROOT.TH1D("nTau_m","nTau_m",100,0,10)
        self.addObject(self.nTau_m)
        self.nMuon_m= ROOT.TH1D("nMuon_m","nMuon_m",100,0,10)
        self.addObject(self.nMuon_m)
        self.nJet_m=ROOT.TH1D("nJet_m","nJet_m",100,0,20)
        self.addObject(self.nJet_m)

        self.GJet_pt_original= ROOT.TH1D("GJet_pt_original","GJet_pt_original",100,0,400)
        self.addObject(self.GJet_pt_original)
        self.GJet_eta_original= ROOT.TH1D("GJet_eta_original","GJet_eta_original",100,-4,4)
        self.addObject(self.GJet_eta_original)
        self.GJet_phi_original= ROOT.TH1D("GJet_phi_original","GJet_phi_original",100,-4,4)
        self.addObject(self.GJet_phi_original)
        self.GJet_mass_original= ROOT.TH1D("GJet_mass_original","GJet_mass_original",100,0,400)
        self.addObject(self.GJet_mass_original)
        self.nTau_original= ROOT.TH1D("nTau_original","nTau_original",100,0,10)
        self.addObject(self.nTau_original)
        self.nMuon_original= ROOT.TH1D("nMuon_original","nMuon_original",100,0,10)
        self.addObject(self.nMuon_original)
        self.nJet_original=ROOT.TH1D("nJet_original","nJet_original",100,0,20)
        self.addObject(self.nJet_original)

	self.GMuon_pt_tpcheck_c= ROOT.TH1D("GMuon_pt_tpcheck_c","GMuon_pt_tpcheck_c",100,0,400)
	self.addObject(self.GMuon_pt_tpcheck_c)
	self.GMuon_pt_tpcheck_m= ROOT.TH1D("GMuon_pt_tpcheck_m","GMuon_pt_tpcheck_m",100,0,400)
        self.addObject(self.GMuon_pt_tpcheck_m)
	self.GMuon_pt_tpcheck_p= ROOT.TH1D("GMuon_pt_tpcheck_p","GMuon_pt_tpcheck_p",100,0,400)
        self.addObject(self.GMuon_pt_tpcheck_p)
	self.GMuon_pt_tpcheck_original= ROOT.TH1D("GMuon_pt_tpcheck_original","GMuon_pt_tpcheck_original",100,0,400)
        self.addObject(self.GMuon_pt_tpcheck_original)



	self.GMuon_pfisoid_original = ROOT.TH1D("GMuon_pfisoid_original","GMuon_pfisoid_original", 100, 0, 10)
	self.addObject(self.GMuon_pfisoid_original)
	self.GMuon_pfisoid_c = ROOT.TH1D("GMuon_pfisoid_c","GMuon_pfisoid_c", 100, 0, 10)
        self.addObject(self.GMuon_pfisoid_c)

        self.GMuon_pt_ss = ROOT.TH1D("GMuon_pt_ss","GMuon_pt_ss",100,0,400)
        self.addObject(self.GMuon_pt_ss)
        self.GMuon_eta_ss = ROOT.TH1D("GMuon_eta_ss","GMuon_eta_ss",100,-4,4)
        self.addObject(self.GMuon_eta_ss)
        self.GMuon_phi_ss = ROOT.TH1D("GMuon_phi_ss","GMuon_phi_ss",100,-4,4)
        self.addObject(self.GMuon_phi_ss)
        self.GMuon_mass_ss = ROOT.TH1D("GMuon_mass_ss","GMuon_mass_ss",100,0,100)
        self.addObject(self.GMuon_mass_ss)
        self.GMuon_charge_ss = ROOT.TH1D("GMuon_charge_ss","GMuon_charge_ss",100,-1.2,1.2)
        self.addObject(self.GMuon_charge_ss)
        self.GMuon_ntrackerlayers_ss = ROOT.TH1D("GMuon_ntrackerlayers_ss","GMuon_ntrackerlayers_ss",100,0,10)
        self.addObject(self.GMuon_ntrackerlayers_ss)
        self.GMuon_pfisoid_ss = ROOT.TH1D("GMuon_pfisoid_ss","GMuon_pfisoid_ss",100,0,10)
        self.addObject(self.GMuon_pfisoid_ss)
        self.Z_massTau_ss = ROOT.TH1D("Z_massTau_ss","Z_massTau_ss",100,0,400)
        self.addObject(self.Z_massTau_ss)
	self.GPZeta_Tau_ss =ROOT.TH1D("GPZeta_Tau_ss", "GPZeta_Tau_ss", 100, -100, 100)
        self.addObject(self.GPZeta_Tau_ss)
        self.GTransMass_ss= ROOT.TH1D("GTransMass_ss","GTransMass_ss",100,0,50)
        self.addObject(self.GTransMass_ss)


    def analyze(self, event):
        """process event, return True (go to next module) or False (fail, go to next event)"""
	MuonMuon= True
    	weights = [event.GSF_central*event.GSF_HEM, event.GSF_plus*event.GSF_HEM,event.GSF_minus*event.GSF_HEM]

    	self.Central_Scale_Dist.Fill(weights[0])
    	self.Upper_Scale_Dist.Fill(weights[1])
    	self.Lower_Scale_Dist.Fill(weights[2])
    	self.Rochester_Scale_Dist.Fill(event.GSF_rochester)
   	self.ID_ISO_Trig_Scale_Dist.Fill(event.GSF_id_iso_trig)
        self.HEM_Scale_Dist.Fill(event.GSF_HEM)
        self.Pileup_Central_Scale_Dist.Fill(event.GSF_pileup_central)
    	self.Pileup_Upper_Scale_Dist.Fill(event.GSF_pileup_plus)
    	self.Pileup_Lower_Scale_Dist.Fill(event.GSF_pileup_minus)

	qcd_sf = 1

        if np.signbit(event.GMuon_charge) == np.signbit(event.GTau_charge) and event.GTau_pt >0:
            self.GMuon_pt_ss.Fill(event.GMuon_pt,weights[0]*qcd_sf)
            self.GMuon_eta_ss.Fill(event.GMuon_eta,weights[0]*qcd_sf)
            self.GMuon_phi_ss.Fill(event.GMuon_phi,weights[0]*qcd_sf)
            self.GMuon_mass_ss.Fill(event.GMuon_mass,weights[0]*qcd_sf)
            self.GMuon_charge_ss.Fill(event.GMuon_charge,weights[0]*qcd_sf)
            self.GMuon_ntrackerlayers_ss.Fill(event.GMuon_ntrackerlayers,weights[0]*qcd_sf)
            self.GMuon_pfisoid_ss.Fill(event.GMuon_pfisoid,weights[0]*qcd_sf)
	    self.Z_massTau_ss.Fill(event.Z_massTau,weights[0]*qcd_sf)
            self.GPZeta_Tau_ss.Fill(event.GPZeta_Tau,weights[0])
            self.GPZeta_TP_ss.Fill(event.GPZeta_TP,weights[0])
            self.GTransMass_ss.Fill(event.GTransMass,weights[0])
	   


	self.GnJets_corrected.Fill(event.GnJets_corrected)
	self.GnJets_corrected_c.Fill(event.GnJets_corrected,weights[0])
	self.GnJets_corrected_p.Fill(event.GnJets_corrected,weights[1])
	self.GnJets_corrected_m.Fill(event.GnJets_corrected,weights[2])

	self.GJet_pt_original.Fill(event.GJet_pt)
        self.GJet_eta_original.Fill(event.GJet_eta)
        self.GJet_phi_original.Fill(event.GJet_phi)
        self.GJet_mass_original.Fill(event.GJet_mass)
	self.nTau_original.Fill(event.nTau)
	self.nMuon_original.Fill(event.nMuon)

 	self.GJet_pt_c.Fill(event.GJet_pt,weights[0])
        self.GJet_eta_c.Fill(event.GJet_eta,weights[0])
        self.GJet_phi_c.Fill(event.GJet_phi,weights[0])
        self.GJet_mass_c.Fill(event.GJet_mass,weights[0])
        self.nTau_c.Fill(event.nTau,weights[0])
        self.nMuon_c.Fill(event.nMuon,weights[0])

 	self.GJet_pt_p.Fill(event.GJet_pt,weights[1])
        self.GJet_eta_p.Fill(event.GJet_eta,weights[1])
        self.GJet_phi_p.Fill(event.GJet_phi,weights[1])
        self.GJet_mass_p.Fill(event.GJet_mass,weights[1])
        self.nTau_p.Fill(event.nTau,weights[1])
        self.nMuon_p.Fill(event.nMuon,weights[1])

        self.GJet_pt_m.Fill(event.GJet_pt,weights[2])
        self.GJet_eta_m.Fill(event.GJet_eta,weights[2])
        self.GJet_phi_m.Fill(event.GJet_phi,weights[2])
        self.GJet_mass_m.Fill(event.GJet_mass,weights[2])
        self.nTau_m.Fill(event.nTau,weights[2])
        self.nMuon_m.Fill(event.nMuon,weights[2])

	self.nJet_original.Fill(event.nJet)
	self.nJet_c.Fill(event.nJet,weights[0])
	self.nJet_p.Fill(event.nJet,weights[1])
	self.nJet_m.Fill(event.nJet,weights[2])



	self.GnMuon_original.Fill(event.GnMuon)
	self.GMuon_pt_original.Fill(event.GMuon_pt)
	self.GMuon_eta_original.Fill(event.GMuon_eta)
	self.GMuon_phi_original.Fill(event.GMuon_phi)
	self.GMuon_mass_original.Fill(event.GMuon_mass)
    	self.GMuon_charge_original.Fill(event.GMuon_charge)
	if event.GTau_pt > 0:
    		self.GTau_charge_original.Fill(event.GTau_charge)
		self.GnTau_original.Fill(event.GnTau)
        	self.GTau_pt_original.Fill(event.GTau_pt)
        	self.GTau_eta_original.Fill(event.GTau_eta)
        	self.GTau_phi_original.Fill(event.GTau_phi)
        	self.GTau_mass_original.Fill(event.GTau_mass)
        self.GNPV_original.Fill(event.GNPV)




	if event.GTau_pt >0 and event.GTwoProng_pt >0:
	        self.TPTauDeltaR_original.Fill(event.TPTauDeltaR)

        if event.GTwoProng_pt >0: self.GTPnTracks_original.Fill(event.GTPnTracks)
        self.GMET_original.Fill(event.GMET)

#	if MuonMuon:
#		self.Z_massMuonMuon_original.Fill(event.Z_massMuonMuon)
#	        self.GMuon_pt2_original.Fill(event.GMuon_pt2)
#	        self.GMuon_eta2_original.Fill(event.GMuon_eta2)
#	        self.GMuon_phi2_original.Fill(event.GMuon_phi2)
#	        self.GMuon_mass2_original.Fill(event.GMuon_mass2)

    	if np.signbit(event.GMuon_charge) != np.signbit(event.GTau_charge) and event.GMuon_charge != 0 and event.GTau_charge !=0 and event.GTau_pt >0:
	    	self.GnMuon_m.Fill(event.GnMuon,weights[2])
        	self.GMuon_pt_m.Fill(event.GMuon_pt,weights[2]*qcd_sf)
        	self.GMuon_eta_m.Fill(event.GMuon_eta,weights[2]*qcd_sf)
        	self.GMuon_phi_m.Fill(event.GMuon_phi,weights[2]*qcd_sf)
        	self.GMuon_mass_m.Fill(event.GMuon_mass,weights[2]*qcd_sf)
        	self.GMuon_charge_m.Fill(event.GMuon_charge,weights[2]*qcd_sf)
        	self.Z_massTau_m.Fill(event.Z_massTau,weights[2]*qcd_sf)

	        self.GnMuon_p.Fill(event.GnMuon,weights[1])
	    	self.GMuon_pt_p.Fill(event.GMuon_pt,weights[1]*qcd_sf)
	    	self.GMuon_eta_p.Fill(event.GMuon_eta,weights[1]*qcd_sf)
	    	self.GMuon_phi_p.Fill(event.GMuon_phi,weights[1]*qcd_sf)
	    	self.GMuon_mass_p.Fill(event.GMuon_mass,weights[1]*qcd_sf)
	        self.GMuon_charge_p.Fill(event.GMuon_charge,weights[1]*qcd_sf)
	        self.Z_massTau_p.Fill(event.Z_massTau,weights[1]*qcd_sf)

	        self.GnMuon_c.Fill(event.GnMuon,weights[0])
	        self.GMuon_pt_c.Fill(event.GMuon_pt,weights[0]*qcd_sf)
	        self.GMuon_eta_c.Fill(event.GMuon_eta,weights[0]*qcd_sf)
	        self.GMuon_phi_c.Fill(event.GMuon_phi,weights[0]*qcd_sf)
	        self.GMuon_mass_c.Fill(event.GMuon_mass,weights[0]*qcd_sf)
	        self.GMuon_charge_c.Fill(event.GMuon_charge,weights[0]*qcd_sf)
	        self.Z_massTau_c.Fill(event.Z_massTau,weights[0]*qcd_sf)
	        self.Z_massTau_original.Fill(event.Z_massTau)
		self.GPZeta_Tau_c.Fill(event.GPZeta_Tau,weights[0])
                self.GTransMass_c.Fill(event.GTransMass,weights[0])


	if event.GTwoProng_pt >0:
		self.Z_massTP_original.Fill(event.Z_massTP)
		self.Z_massTP_c.Fill(event.Z_massTP,weights[0]*qcd_sf)
		self.Z_massTP_p.Fill(event.Z_massTP,weights[1]*qcd_sf)
	        self.Z_massTP_m.Fill(event.Z_massTP,weights[2]*qcd_sf)


    		if event.TPTauDeltaR > 0.1:
        		self.Z_massTPIso_original.Fill(event.Z_massTP)
        		self.Z_massTPIso_c.Fill(event.Z_massTP,weights[0]*qcd_sf)
        		self.Z_massTPIso_p.Fill(event.Z_massTP,weights[1]*qcd_sf)
        		self.Z_massTPIso_m.Fill(event.Z_massTP,weights[2]*qcd_sf)
        		self.GTau_iso_pt_m.Fill(event.GTau_pt,weights[2])
        		self.GTwoProng_iso_pt_m.Fill(event.GTwoProng_pt,weights[2])
        		self.GTau_iso_phi_m.Fill(event.GTau_phi,weights[2])
        		self.GTwoProng_iso_phi_m.Fill(event.GTwoProng_phi,weights[2])
        		self.GTau_iso_eta_m.Fill(event.GTau_eta,weights[2])
        		self.GTwoProng_iso_eta_m.Fill(event.GTwoProng_eta,weights[2])
        		self.GTau_iso_pt_p.Fill(event.GTau_pt,weights[1])
        		self.GTwoProng_iso_pt_p.Fill(event.GTwoProng_pt,weights[1])
        		self.GTau_iso_phi_p.Fill(event.GTau_phi,weights[1])
        		self.GTwoProng_iso_phi_p.Fill(event.GTwoProng_phi,weights[1])
        		self.GTau_iso_eta_p.Fill(event.GTau_eta,weights[1])
        		self.GTwoProng_iso_eta_p.Fill(event.GTwoProng_eta,weights[1])
        		self.GTau_iso_pt_original.Fill(event.GTau_pt)
        		self.GTwoProng_iso_pt_original.Fill(event.GTwoProng_pt)
        		self.GTau_iso_phi_original.Fill(event.GTau_phi)
        		self.GTwoProng_iso_phi_original.Fill(event.GTwoProng_phi)
        		self.GTau_iso_eta_original.Fill(event.GTau_eta)
        		self.GTwoProng_iso_eta_original.Fill(event.GTwoProng_eta)
        		self.GTau_iso_pt_c.Fill(event.GTau_pt,weights[0])
        		self.GTwoProng_iso_pt_c.Fill(event.GTwoProng_pt,weights[0])
        		self.GTau_iso_phi_c.Fill(event.GTau_phi,weights[0])
        		self.GTwoProng_iso_phi_c.Fill(event.GTwoProng_phi,weights[0])
        		self.GTau_iso_eta_c.Fill(event.GTau_eta,weights[0])
        		self.GTwoProng_iso_eta_c.Fill(event.GTwoProng_eta,weights[0])

    		if event.GTPnTracks == 3:
        		self.Z_massTP3track_original.Fill(event.Z_massTP)
        		self.Z_massTP3track_c.Fill(event.Z_massTP,weights[0]*qcd_sf)
        		self.Z_massTP3track_p.Fill(event.Z_massTP,weights[1]*qcd_sf)
        		self.Z_massTP3track_m.Fill(event.Z_massTP,weights[2]*qcd_sf)
        		self.GTwoProng_3track_pt_m.Fill(event.GTwoProng_pt,weights[2])
        		self.GTwoProng_3track_phi_m.Fill(event.GTwoProng_phi,weights[2])
        		self.GTwoProng_3track_eta_m.Fill(event.GTwoProng_eta,weights[2])
        		self.GTwoProng_3track_pt_p.Fill(event.GTwoProng_pt,weights[1])
        		self.GTwoProng_3track_phi_p.Fill(event.GTwoProng_phi,weights[1])
        		self.GTwoProng_3track_eta_p.Fill(event.GTwoProng_eta,weights[1])
        		self.GTwoProng_3track_pt_original.Fill(event.GTwoProng_pt)
        		self.GTwoProng_3track_phi_original.Fill(event.GTwoProng_phi)
        		self.GTwoProng_3track_eta_original.Fill(event.GTwoProng_eta)
        		self.GTwoProng_3track_pt_c.Fill(event.GTwoProng_pt,weights[0])
        		self.GTwoProng_3track_phi_c.Fill(event.GTwoProng_phi,weights[0])
        		self.GTwoProng_3track_eta_c.Fill(event.GTwoProng_eta,weights[0])

		if 0 <= event.TPTauDeltaR <= 0.1:
        		self.GTau_noiso_pt_m.Fill(event.GTau_pt,weights[2])
        		self.GTwoProng_noiso_pt_m.Fill(event.GTwoProng_pt,weights[2])
        		self.GTau_noiso_phi_m.Fill(event.GTau_phi,weights[2])
        		self.GTwoProng_noiso_phi_m.Fill(event.GTwoProng_phi,weights[2])
        		self.GTau_noiso_eta_m.Fill(event.GTau_eta,weights[2])
        		self.GTwoProng_noiso_eta_m.Fill(event.GTwoProng_eta,weights[2])
        		self.GTau_noiso_pt_p.Fill(event.GTau_pt,weights[1])
        		self.GTwoProng_noiso_pt_p.Fill(event.GTwoProng_pt,weights[1])
        		self.GTau_noiso_phi_p.Fill(event.GTau_phi,weights[1])
        		self.GTwoProng_noiso_phi_p.Fill(event.GTwoProng_phi,weights[1])
        		self.GTau_noiso_eta_p.Fill(event.GTau_eta,weights[1])
        		self.GTwoProng_noiso_eta_p.Fill(event.GTwoProng_eta,weights[1])
        		self.GTau_noiso_pt_original.Fill(event.GTau_pt)
        		self.GTwoProng_noiso_pt_original.Fill(event.GTwoProng_pt)
        		self.GTau_noiso_phi_original.Fill(event.GTau_phi)
        		self.GTwoProng_noiso_phi_original.Fill(event.GTwoProng_phi)
        		self.GTau_noiso_eta_original.Fill(event.GTau_eta)
        		self.GTwoProng_noiso_eta_original.Fill(event.GTwoProng_eta)
        		self.GTau_noiso_pt_c.Fill(event.GTau_pt,weights[0])
        		self.GTwoProng_noiso_pt_c.Fill(event.GTwoProng_pt,weights[0])
        		self.GTwoProng_noiso_phi_c.Fill(event.GTwoProng_phi,weights[0])
        		self.GTau_noiso_eta_c.Fill(event.GTau_eta,weights[0])
        		self.GTwoProng_noiso_eta_c.Fill(event.GTwoProng_eta,weights[0])
        		self.GTau_noiso_phi_c.Fill(event.GTau_phi,weights[0])




	if event.GTau_pt>0:
	        self.GTau_charge_m.Fill(event.GTau_charge,weights[2]*qcd_sf)
	        self.GnTau_m.Fill(event.GnTau,weights[2])
	        self.GTau_pt_m.Fill(event.GTau_pt,weights[2])
	        self.GTau_eta_m.Fill(event.GTau_eta,weights[2])
	        self.GTau_phi_m.Fill(event.GTau_phi,weights[2])
	        self.GTau_mass_m.Fill(event.GTau_mass,weights[2])
        self.GNPV_m.Fill(event.GNPV,weights[2])
	if event.GTau_pt >0 and event.GTwoProng_pt >0:
	        self.TPTauDeltaR_m.Fill(event.TPTauDeltaR,weights[2])

        if event.GTwoProng_pt>0: self.GTPnTracks_m.Fill(event.GTPnTracks,weights[2])
        self.GMET_m.Fill(event.GMET,weights[2])

 #       if MuonMuon:
 #               self.Z_massMuonMuon_m.Fill(event.Z_massMuonMuon,weights[2])
 #               self.GMuon_pt2_m.Fill(event.GMuon_pt2,weights[2])
 #               self.GMuon_eta2_m.Fill(event.GMuon_eta2,weights[2])
 #               self.GMuon_phi2_m.Fill(event.GMuon_phi2,weights[2])
 #               self.GMuon_mass2_m.Fill(event.GMuon_mass2,weights[2])


	if event.GTau_pt>0:
	        self.GTau_charge_p.Fill(event.GTau_charge,weights[1]*qcd_sf)
	    	self.GnTau_p.Fill(event.GnTau,weights[1])
	        self.GTau_pt_p.Fill(event.GTau_pt,weights[1])
	        self.GTau_eta_p.Fill(event.GTau_eta,weights[1])
	        self.GTau_phi_p.Fill(event.GTau_phi,weights[1])
	        self.GTau_mass_p.Fill(event.GTau_mass,weights[1])
        self.GNPV_p.Fill(event.GNPV,weights[1])


        if event.GTau_pt >0 and event.GTwoProng_pt >0:
		self.TPTauDeltaR_p.Fill(event.TPTauDeltaR,weights[1])
        if event.GTwoProng_pt >0: self.GTPnTracks_p.Fill(event.GTPnTracks,weights[1])
        self.GMET_p.Fill(event.GMET,weights[1])
  #      if MuonMuon:
  #      	self.Z_massMuonMuon_p.Fill(event.Z_massMuonMuon,weights[1])
  #      	self.GMuon_pt2_p.Fill(event.GMuon_pt2,weights[1])
  #      	self.GMuon_eta2_p.Fill(event.GMuon_eta2,weights[1])
  #      	self.GMuon_phi2_p.Fill(event.GMuon_phi2,weights[1])
  #              self.GMuon_mass2_p.Fill(event.GMuon_mass2,weights[1])




	if event.GTau_pt >0:
	        self.GTau_charge_c.Fill(event.GTau_charge,weights[0]*qcd_sf)
		self.GnTau_c.Fill(event.GnTau,weights[0])
        	self.GTau_pt_c.Fill(event.GTau_pt,weights[0])
        	self.GTau_eta_c.Fill(event.GTau_eta,weights[0])
        	self.GTau_phi_c.Fill(event.GTau_phi,weights[0])
        	self.GTau_mass_c.Fill(event.GTau_mass,weights[0])
        self.GNPV_c.Fill(event.GNPV,weights[0])

        if event.GTau_pt >0 and event.GTwoProng_pt >0:
		self.TPTauDeltaR_c.Fill(event.TPTauDeltaR,weights[0])
        if event.GTwoProng_pt >0: self.GTPnTracks_c.Fill(event.GTPnTracks,weights[0])
        self.GMET_c.Fill(event.GMET,weights[0])

#	self.MCTC.Fill(event.GMCTC)
	if event.GTwoProng_pt >0:
		self.GMuon_pt_tpcheck_original.Fill(event.GMuon_pt_tpcheck)
		self.GMuon_pt_tpcheck_c.Fill(event.GMuon_pt_tpcheck,weights[0]*qcd_sf)
		self.GMuon_pt_tpcheck_p.Fill(event.GMuon_pt_tpcheck,weights[1]*qcd_sf)
		self.GMuon_pt_tpcheck_m.Fill(event.GMuon_pt_tpcheck,weights[2]*qcd_sf)


	self.GMuon_pfisoid_original.Fill(event.GMuon_pfisoid)
        self.GMuon_pfisoid_c.Fill(event.GMuon_pfisoid, weights[0]*qcd_sf)


   #     if MuonMuon:
   #             self.Z_massMuonMuon_c.Fill(event.Z_massMuonMuon,weights[0]*qcd_sf)
   #             self.GMuon_pt2_c.Fill(event.GMuon_pt2,weights[0]*qcd_sf)
   #             self.GMuon_eta2_c.Fill(event.GMuon_eta2,weights[0]*qcd_sf)
   #             self.GMuon_phi2_c.Fill(event.GMuon_phi2,weights[0]*qcd_sf)
   #             self.GMuon_mass2_c.Fill(event.GMuon_mass2,weights[0]*qcd_sf)

	if event.GnJets_corrected ==0:
		self.Z_massTau_j0.Fill(event.Z_massTau)
		self.Z_massTau_j0_c.Fill(event.Z_massTau,weights[0]*qcd_sf)
		self.Z_massTau_j0_p.Fill(event.Z_massTau,weights[1]*qcd_sf)
		self.Z_massTau_j0_m.Fill(event.Z_massTau,weights[2]*qcd_sf)

	if event.GnJets_corrected ==1:
        	self.Z_massTau_j1.Fill(event.Z_massTau)
        	self.Z_massTau_j1_c.Fill(event.Z_massTau,weights[0]*qcd_sf)
        	self.Z_massTau_j1_p.Fill(event.Z_massTau,weights[1]*qcd_sf)
        	self.Z_massTau_j1_m.Fill(event.Z_massTau,weights[2]*qcd_sf)

	if event.GnJets_corrected ==2:
        	self.Z_massTau_j2.Fill(event.Z_massTau)
        	self.Z_massTau_j2_c.Fill(event.Z_massTau,weights[0]*qcd_sf)
        	self.Z_massTau_j2_p.Fill(event.Z_massTau,weights[1]*qcd_sf)
        	self.Z_massTau_j2_m.Fill(event.Z_massTau,weights[2]*qcd_sf)

	if event.GnJets_corrected ==3:
        	self.Z_massTau_j3.Fill(event.Z_massTau)
        	self.Z_massTau_j3_c.Fill(event.Z_massTau,weights[0]*qcd_sf)
        	self.Z_massTau_j3_p.Fill(event.Z_massTau,weights[1]*qcd_sf)
        	self.Z_massTau_j3_m.Fill(event.Z_massTau,weights[2]*qcd_sf)

	if event.GnJets_corrected ==4:
        	self.Z_massTau_j4.Fill(event.Z_massTau)
        	self.Z_massTau_j4_c.Fill(event.Z_massTau,weights[0]*qcd_sf)
        	self.Z_massTau_j4_p.Fill(event.Z_massTau,weights[1]*qcd_sf)
        	self.Z_massTau_j4_m.Fill(event.Z_massTau,weights[2]*qcd_sf)

	if event.GnJets_corrected ==5:
        	self.Z_massTau_j5.Fill(event.Z_massTau)
        	self.Z_massTau_j5_c.Fill(event.Z_massTau,weights[0]*qcd_sf)
        	self.Z_massTau_j5_p.Fill(event.Z_massTau,weights[1]*qcd_sf)
        	self.Z_massTau_j5_m.Fill(event.Z_massTau,weights[2]*qcd_sf)


        return True
